## ANA-522 
## Mod02 Week03 Assignment: NumPy 
## Due: Sunday of week 3 at midnight

**Instructions:**

- Submit your work as a .ipynb or PDF file on blackboard.

- Please include your name in the filename of your submission

- Please make sure all code is executed and displays the corresponding output. If the corresponding output is not displayed, no points will be given.

- *Note:* Each question includes sample output that you can use to check if your solution is correct.

<br>

### Import the NumPy Library

In [166]:
import numpy as np

### 1.  Create a null vector (zeros) of size 40
(a) create in one dimension, as array A1  
(b) create in two dimension with 8 rows and 5 columns, as array A2  
(c) create a new array as A3, which is a copy of A2, except that all values on the third column are 1     
Print A1, A2, and A3.

<pre>
Array A1:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array A2:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
Array A3:
 [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]] 
</pre>

In [167]:
A1 = np.zeros(40)
A2 = np.zeros((8, 5))

A3 = np.copy(A2)
A3[:, 2] = 1 # row, column 
print("Array A1")
print(A1)
print("Array A2")
print(A2)
print("Array A3")
print(A3)

Array A1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array A2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array A3
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


### 2. Create a vector with values ranging from 1 to 40 
(a) create in one dimension, as array B1  
(b) create in two dimenion with 8 rows and 5 columns, as array B2  
(c) create a new array B3 by adding B2 with A3       
(d) create a new array B4 with the values from B3 subtracted by 11   
Print B1, B2, B3, and B4
<pre>
Array B1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
Array B2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
Array B3:
 [[ 1.  2.  4.  4.  5.]
 [ 6.  7.  9.  9. 10.]
 [11. 12. 14. 14. 15.]
 [16. 17. 19. 19. 20.]
 [21. 22. 24. 24. 25.]
 [26. 27. 29. 29. 30.]
 [31. 32. 34. 34. 35.]
 [36. 37. 39. 39. 40.]]
Array B4:
 [[-10.  -9.  -7.  -7.  -6.]
 [ -5.  -4.  -2.  -2.  -1.]
 [  0.   1.   3.   3.   4.]
 [  5.   6.   8.   8.   9.]
 [ 10.  11.  13.  13.  14.]
 [ 15.  16.  18.  18.  19.]
 [ 20.  21.  23.  23.  24.]
 [ 25.  26.  28.  28.  29.]]
 </pre>

In [168]:
B1 = np.arange(1,41)
B2 = B1.reshape(8, 5)
B3 = A3 + B2
B4 = B3 - 11

print("Array B1")
print(B1)
print("Array B2")
print(B2)
print("Array B3")
print(B3)
print("Array B4")
print(B4)

Array B1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
Array B2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
Array B3
[[ 1.  2.  4.  4.  5.]
 [ 6.  7.  9.  9. 10.]
 [11. 12. 14. 14. 15.]
 [16. 17. 19. 19. 20.]
 [21. 22. 24. 24. 25.]
 [26. 27. 29. 29. 30.]
 [31. 32. 34. 34. 35.]
 [36. 37. 39. 39. 40.]]
Array B4
[[-10.  -9.  -7.  -7.  -6.]
 [ -5.  -4.  -2.  -2.  -1.]
 [  0.   1.   3.   3.   4.]
 [  5.   6.   8.   8.   9.]
 [ 10.  11.  13.  13.  14.]
 [ 15.  16.  18.  18.  19.]
 [ 20.  21.  23.  23.  24.]
 [ 25.  26.  28.  28.  29.]]


### 3. Create a 12x12 matrix and fill it with a checkerboard pattern
(a) first row and first column starts from 0    
(b) first row and first column starts from 1  
(c) with all numbers are 1 (integer)  
(d) with all numbers are 1.0 (floating-point)  
Print all matrix above.

<pre>
Checkerboard pattern starts from 0:
[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]

Checkerboard pattern starts from 1:
[[1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]]

All integer ones:
[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]

All floating-point ones:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 </pre>

In [169]:
CheckerBoardPattern = np.zeros((12, 12))
CheckerBoardPattern[::2, 1::2] = 1 
CheckerBoardPattern[1::2, ::2] = 1

print('Check board pattern starts from zero')
print(CheckerBoardPattern)


CheckerBoardPattern = np.zeros((12, 12))
CheckerBoardPattern[::2, ::2] = 1  # Rows starting with 0, fill in 1s at odd columns
CheckerBoardPattern[1::2, 1::2] = 1  # Rows starting with 1, fill in 1s at even columns

print('Check board pattern starts from one')
print(CheckerBoardPattern)

CheckerBoardPattern = np.ones((12, 12)).astype(int)
print("All integers are ones")
print(CheckerBoardPattern)

CheckerBoardPattern_f = CheckerBoardPattern.astype(float)
print("All floating-points ones")
print(CheckerBoardPattern_f)


Check board pattern starts from zero
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
Check board pattern starts from one
[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 

### 4. Create a matrix, block segments, and integrations
(a) create matrix X of 3 rows and 12 columns of random integers range [0,100]     
(b) create matrix XA of 3 rows and 3 columns of subset matrix of X with all rows, and the first three columns (0 to 2)   
(c) create matrix XB of 3 rows and 3 columns of subset matrix of X with all rows, and the second quarter columns (3 to 5)   
(d) create matrix XC of 3 rows and 3 columns of subset matrix of X with all rows, and tbe third quarter columns (6 to 8)   
(e) create matrix XD of 3 rows and 3 columns of subset matrix of X with all rows, and tbe fourth quarter columns (9 to 11)   
(f) create matrix Y of 3 rows and 12 columns by putting together in the order of XD XA XB XC from column index 0 to 11  
(g) create matrix Z of 12 rows and 3 columns by putting together vertically in the order of XD XA XB XC

>Hint: Use np.concatenate() to put two matrixes together (avaible from reading assignments.) 

<pre>
Matrix X:
[[ 3 54 99 72 41 64 54 48 57 15 51 73]
 [59 28 95 93 75 88 21 79 98 83 75 61]
 [ 0 70 54 40 37 38 68 67 90 58 46 58]]
Matrix XA:
[[ 3 54 99]
 [59 28 95]
 [ 0 70 54]]
Matrix XB:
[[72 41 64]
 [93 75 88]
 [40 37 38]]
Matrix XC:
[[54 48 57]
 [21 79 98]
 [68 67 90]]
Matrix XD:
[[15 51 73]
 [83 75 61]
 [58 46 58]]
Matrix Y:
[[15 51 73  3 54 99 72 41 64 54 48 57]
 [83 75 61 59 28 95 93 75 88 21 79 98]
 [58 46 58  0 70 54 40 37 38 68 67 90]]
Matrix Z:
[[15 51 73]
 [83 75 61]
 [58 46 58]
 [ 3 54 99]
 [59 28 95]
 [ 0 70 54]
 [72 41 64]
 [93 75 88]
 [40 37 38]
 [54 48 57]
 [21 79 98]
 [68 67 90]]
 </pre>

In [170]:
#create matrix X of 3 rows and 12 columns of random integers range [0,100]     
X = np.random.randint(0, 101, (3, 12))
XA = X[:,:3]
XB = X[:,3:6]
XC = X[:,6:9]
XD = X[:,9:]

Y = np.concatenate((XA, XB, XC, XD), axis=1)
Z = Y.T
# Z = np.concatenate((XA, XB, XC, XD), axis=0)

print('Matrix X')
print(X)

print('Matrix XA')
print(XA)

print('Matrix XB')
print(XB)

print('Matrix XC')
print(XC)

print('Matrix XD')
print(XD)

print('Matrix Y')
print(Y)

print('Matrix Z')
print(Z)


Matrix X
[[37 16 61 51 68  0 91 28 14 96 14 52]
 [23 27 93 69 71 18 17 91 63 36 50 20]
 [85 73 66 50 74 37 90 60  8 20 27 43]]
Matrix XA
[[37 16 61]
 [23 27 93]
 [85 73 66]]
Matrix XB
[[51 68  0]
 [69 71 18]
 [50 74 37]]
Matrix XC
[[91 28 14]
 [17 91 63]
 [90 60  8]]
Matrix XD
[[96 14 52]
 [36 50 20]
 [20 27 43]]
Matrix Y
[[37 16 61 51 68  0 91 28 14 96 14 52]
 [23 27 93 69 71 18 17 91 63 36 50 20]
 [85 73 66 50 74 37 90 60  8 20 27 43]]
Matrix Z
[[37 23 85]
 [16 27 73]
 [61 93 66]
 [51 69 50]
 [68 71 74]
 [ 0 18 37]
 [91 17 90]
 [28 91 60]
 [14 63  8]
 [96 36 20]
 [14 50 27]
 [52 20 43]]


### 5. Create the following two matrixes in the program
<pre>
A = [[1 2]
     [3 4]
     [5 6]
     [7 8]]
B = [[ 9 10 11 12]
     [13 14 15 16]]
</pre>
and do the matrix multiplication where C = AB  
Print matrixes A, B, and C.

<pre>
Matrix A:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Matrix B:
[[ 9 10 11 12]
 [13 14 15 16]]
Matrix C:
[[ 35  38  41  44]
 [ 79  86  93 100]
 [123 134 145 156]
 [167 182 197 212]]
 </pre>

In [171]:
A = np.arange(1,9).reshape(4,2)
B = np.arange(9,17).reshape(2,4)
C = np.matmul(A, B)

print('Matrix A')
print(A)

print('Matrix B')
print(B)

print('Matrix C')
print(C)

Matrix A
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Matrix B
[[ 9 10 11 12]
 [13 14 15 16]]
Matrix C
[[ 35  38  41  44]
 [ 79  86  93 100]
 [123 134 145 156]
 [167 182 197 212]]


### 6. Vector Operations and Basic Calculations
   
Given 1D arrays A = [4, 9, 16, 25, 36] and B = [2, 3, 4, 5, 6]: 

(a) Create array C by calculating the square root of A  
(b) Create array D by calculating B squared  
(c) Create array E by adding A and B element-wise  
(d) Create array F by dividing A by B element-wise  
(e) Find and print the maximum and minimum values in all arrays  
Print arrays C, D, E, F and the max/min values.


<pre>
Array C:
[ 2.  3.  4.  5.  6.]
Array D:
[ 4  9 16 25 36]
Array E:
[ 6 12 20 30 42]
Array F:
[ 2.  3.  4.  5.  6.]
Maximum values:
A: 36, B: 6, C: 6.0, D: 36, E: 42, F: 6.0
Minimum values:
A: 4, B: 2, C: 2.0, D: 4, E: 6, F: 2.0
</pre>

In [172]:
A = np.arange(2,7)**2
B = np.arange(2,7)
C = np.sqrt(A)
D = B**2
E = A + B
F = A / B

print('Array C')
print(C)

print('Array D')
print(D)

print('Array E')
print(E)

print('Array F')
print(F)

print("Maximum values: ")
print("A:",np.max(A),"B:", np.max(B), "C:",np.max(C),"D:", np.max(D),"E:", np.max(E),"F:", np.max(F))

print("Minimum values: ")
print("A:",np.min(A),"B:", np.min(B), "C:",np.min(C),"D:", np.min(D),"E:", np.min(E),"F:", np.min(F))

Array C
[2. 3. 4. 5. 6.]
Array D
[ 4  9 16 25 36]
Array E
[ 6 12 20 30 42]
Array F
[2. 3. 4. 5. 6.]
Maximum values: 
A: 36 B: 6 C: 6.0 D: 36 E: 42 F: 6.0
Minimum values: 
A: 4 B: 2 C: 2.0 D: 4 E: 6 F: 2.0


### 7. Grade Analysis Matrix 
Create the following matrices and calculations:   
(a) Create a 4x5 matrix G with random integer grades between 60 and 100    
(b) Calculate vector H containing the average grade for each student (row means)    
(c) Calculate vector I containing the average grade for each subject (column means)    
(d) Create matrix J where each element is 1 if above subject average, 0 if below   
(e) Create vector K containing the rank of each student based on their average grade   
Print matrices G, J and vectors H, I, K. 
>Hint: 
>1. Use np.mean(axis=0) for subject averages (columns)
>2. Use np.mean(axis=1) for student averages (rows)
>3. Use np.argsort(H) + 1 for rankings

<pre>
Matrix G:
[[85 92 78 95 88]
 [90 75 89 82 94]
 [77 88 92 85 79]
 [93 87 84 91 86]]   
    
Vector H (Student Averages):
[87.6 86.0 84.2 88.2]     
    
Vector I (Subject Averages):
[86.25 85.5  85.75 88.25 86.75]
    
Matrix J (Above Average = 1):
[[0 1 0 1 1]
 [1 0 1 0 1]
 [0 1 1 0 0]
 [1 1 0 1 0]]     
    
Vector K (Student Rankings):
[2 3 4 1]    
</pre>

In [173]:
G = np.random.randint(60,101,(4,5))
H = np.mean(G,axis = 1)
I = np.mean(G,axis = 0)
J = np.where(G > np.mean(G), 1, 0)
K = np.argsort(-H) + 1


print("Matrix G")  
print(G)
print("Matrix H") 
print(H)
print("Matrix I") 
print(I)
print("Matrix J") 
print(J)
print("Matrix K") 
print(K)

Matrix G
[[78 81 69 84 69]
 [64 92 75 62 72]
 [82 78 79 73 61]
 [64 73 96 84 93]]
Matrix H
[76.2 73.  74.6 82. ]
Matrix I
[72.   81.   79.75 75.75 73.75]
Matrix J
[[1 1 0 1 0]
 [0 1 0 0 0]
 [1 1 1 0 0]
 [0 0 1 1 1]]
Matrix K
[4 1 3 2]


### 8. Create 7x7 matrixes   
(a) P matrix with row values ranging from 0 to 6 
>>Hint for (a): Two steps:
>1. First create a 7x7 zero matrix: P = np.zeros((7,7))
>2. Then add numbers 0-6 to each row: P += np.arange(7)

(b) Q matrix with column values ranging from 0 to 6  
>Hint for (b): One step:
>Simply transpose matrix P: Q = P.T

(c) R matrix with cumulative sum from previous row of matrix Q
>Hint for (c): One step:
>Use cumsum with axis=0: R = Q.cumsum(axis=0)

(d) S matrix with cumulative sum from previous column of matrix Q  
>Hint for (d): One step:
>Use cumsum with axis=1: S = Q.cumsum(axis=1)

(e) T list with cumulative sum from previous value rolled out in order of row and column from matrix Q  
>Hint for (e): One step:
>Use cumsum without axis parameter: T = Q.cumsum()

Print matrix P,Q,R,S, and list T

<pre>
Matrix P:
[[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]
Matrix Q:
[[0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6.]]
Matrix R:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 3.  3.  3.  3.  3.  3.  3.]
 [ 6.  6.  6.  6.  6.  6.  6.]
 [10. 10. 10. 10. 10. 10. 10.]
 [15. 15. 15. 15. 15. 15. 15.]
 [21. 21. 21. 21. 21. 21. 21.]]
Matrix S:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]
 [ 6. 12. 18. 24. 30. 36. 42.]]
List T:
[  0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   5.   6.   7.
   9.  11.  13.  15.  17.  19.  21.  24.  27.  30.  33.  36.  39.  42.
  46.  50.  54.  58.  62.  66.  70.  75.  80.  85.  90.  95. 100. 105.
 111. 117. 123. 129. 135. 141. 147.]
 </pre>

In [174]:
P = np.zeros((7, 7))
P += np.arange(7)

Q= P.T

R = Q.cumsum(axis=0)
S = Q.cumsum(axis=1)
T = Q.cumsum()

print("Matrix P")
print(P)   
print("Matrix Q")
print(Q)
print("Matrix R")
print(R)
print("Matrix S")
print(S)
print("List T")
print(T)    


Matrix P
[[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]
Matrix Q
[[0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6.]]
Matrix R
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 3.  3.  3.  3.  3.  3.  3.]
 [ 6.  6.  6.  6.  6.  6.  6.]
 [10. 10. 10. 10. 10. 10. 10.]
 [15. 15. 15. 15. 15. 15. 15.]
 [21. 21. 21. 21. 21. 21. 21.]]
Matrix S
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]
 [ 6. 12. 18. 24. 30. 36. 42.]]
List T
[  0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   5.   6.   7.
   9.  11.  13.  15.  17.  19.  21.  24.  27.  30.  33.  36.  39.  42.
  46.  50.  54.  58.  62.  66.  70.  75. 